# Generated by Django 3.0.2 on 2020-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_downloadcache_download_error_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadcache',
            name='data_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
