# Generated by Django 3.0.2 on 2020-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_downloadcache_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadcache',
            name='data_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
